sudo: false
language: node_js
node_js:
- '7'
- '8'
install:
- npm i npminstall && npminstall
services:
- mongodb
before_script:
- sleep 15
script:
- npm run ci
after_script:
- npminstall codecov && codecov
